server:
  port: 8761
eureka:
  server:
    ## 不开启自我保护机制
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
